# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main Branch CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  CI: true
  NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: self-hosted

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/-1
      - run: npm ci

      - name: Run Linter
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Compile TypeScript code
        run: npm run compile

      - name: Build Android App
        run: npm run build-android

      - name: Build iOS App
        run: npm run build-ios
